# Generated by Django 4.0.7 on 2022-10-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('fdate', models.DateField()),
                ('ffare', models.FloatField()),
                ('fstart', models.CharField(max_length=20)),
                ('fend', models.CharField(max_length=20)),
            ],
        ),
    ]
