# Generated by Django 4.0.10 on 2023-03-08 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_rename_fend_flight_details_ffrom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight_details',
            old_name='fto',
            new_name='fend',
        ),
        migrations.RenameField(
            model_name='flight_details',
            old_name='ffrom',
            new_name='fstart',
        ),
    ]
